fix: log to new location

diff --git a/bin/dotpackages b/bin/dotpackages
--- a/bin/dotpackages
+++ b/bin/dotpackages
@@ -1,20 +1,19 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-# fallback in case LOG_LIB isn't already set
-LOG_LIB="${LOG_LIB:-/usr/local/bin/log}"
+# fallback in case DOTLOG isn't already set
+DOTLOG="${DOTLOG:-$HOME/.dotfiles/bin/dotlog}"
 
-if [[ -f "$LOG_LIB" ]]; then
-	source "$LOG_LIB"
+if [[ -f "$DOTLOG" ]]; then
+  source "$DOTLOG"
 else
-	echo "⚠️  LOG_LIB not found at $LOG_LIB. Continuing without logging functions."
+  echo "⚠️  DOTLOG not found at $DOTLOG. Continuing without logging functions."
 fi
 
 # constants
 readonly GITHUB_URL="github.com"
 readonly USERNAME="iamnewton"
 readonly REPO="dotpackages"
-readonly LOG="/tmp/$REPO.log"
 readonly INSTALL_DIR="$HOME/.$REPO"
 OS="$(tr '[:upper:]' '[:lower:]' <<<"$(uname)")"
 readonly OS
@@ -22,7 +21,7 @@ readonly OS
 seek_confirmation() {
 	local message=$1
 
-	print_warning "$message"
+	dotlog::warning "$message"
 	read -r -p "Continue? (y/n) " -n 1
 }
 
@@ -37,12 +36,12 @@ npm_package() {
 	local package=$1
 
 	# Test whether npm package is already installed
-	print_process "Checking if $package is installed"
+	dotlog::process "Checking if $package is installed"
 	if ! npm list -g "$package" | grep "$package" &>/dev/null; then
-		print_process "Installing $package"
+		dotlog::process "Installing $package"
 		npm install --global --quiet "$package"
 	else
-		print_process "$package is already installed. Updating."
+		dotlog::process "$package is already installed. Updating."
 		npm update "$package"
 	fi
 }
@@ -50,12 +49,12 @@ npm_package() {
 whalebrew_package() {
 	local package=$1
 
-	print_process "Checking if $package is installed"
+	dotlog::process "Checking if $package is installed"
 	if ! whalebrew list | grep -q "$package"; then
-		print_process "Installing $package"
+		dotlog::process "Installing $package"
 		whalebrew install "$package"
 	else
-		print_process "$package is already installed."
+		dotlog::process "$package is already installed."
 	fi
 }
 
@@ -72,42 +71,42 @@ install_packages() {
 
 # Check for Homebrew; install brew
 if ! type -P 'brew' &>/dev/null; then
-	print_process "Installing Homebrew"
+	dotlog::process "Installing Homebrew"
 	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 
 	# If we're on Linux, insert brew into the path temporarily to be able to use later
 	if [[ "$OS" == "linux" ]]; then
-		print_process "Sourcing Homebrew to PATH"
+		dotlog::process "Sourcing Homebrew to PATH"
 		eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
 	fi
 
-	[[ $? ]] && print_success "Homebrew installed"
+	[[ $? ]] && dotlog::success "Homebrew installed"
 fi
 
 # If missing, download and extract the dotpackages repository
 # @TODO: create upgrade command
-# print_process "$REPO already installed.  Upgrading $REPO"
+# dotlog::process "$REPO already installed.  Upgrading $REPO"
 # dotpackages
 if ! [[ -d "$INSTALL_DIR" ]]; then
-	print_warning "No $INSTALL_DIR found"
+	dotlog::warning "No $INSTALL_DIR found"
 
-	print_process "Creating directory at $INSTALL_DIR and setting permissions"
+	dotlog::process "Creating directory at $INSTALL_DIR and setting permissions"
 	mkdir -p "$INSTALL_DIR"
 
-	print_process "Downloading repository to /tmp directory"
+	dotlog::process "Downloading repository to /tmp directory"
 	# (-#) shows the progress bar as # sign
 	# (-f) fail silently
 	# (-L) follow the headers
 	# (-o) output to a file
 	curl -#fLo /tmp/dotpackages.tar.gz "https://$GITHUB_URL/$USERNAME/$REPO/tarball/main"
 
-	print_process "Extracting files to $INSTALL_DIR"
+	dotlog::process "Extracting files to $INSTALL_DIR"
 	tar -zxf "/tmp/$REPO.tar.gz" --strip-components 1 -C "$INSTALL_DIR"
 
-	print_process "Removing tarball from /tmp directory"
+	dotlog::process "Removing tarball from /tmp directory"
 	rm -rf "/tmp/$REPO.tar.gz"
 
-	[[ $? ]] && print_success "$INSTALL_DIR created, repository downloaded and extracted"
+	[[ $? ]] && dotlog::success "$INSTALL_DIR created, repository downloaded and extracted"
 fi
 
 if ! [[ -d "$INSTALL_DIR/.git" ]]; then
@@ -115,91 +114,91 @@ if ! [[ -d "$INSTALL_DIR/.git" ]]; then
 	cd "$INSTALL_DIR" || exit
 
 	# Initialize the git repository if it's missing
-	print_process "Initializing git repository"
+	dotlog::process "Initializing git repository"
 	git init
 
-	print_process "Setting main as the default branch"
+	dotlog::process "Setting main as the default branch"
 	git branch -m main
 
-	print_process "Adding https://$GITHUB_URL/$USERNAME/$REPO.git as origin"
+	dotlog::process "Adding https://$GITHUB_URL/$USERNAME/$REPO.git as origin"
 	git remote add origin "https://$GITHUB_URL/$USERNAME/$REPO.git"
 
-	print_process "Downloading changes from origin"
+	dotlog::process "Downloading changes from origin"
 	git fetch origin main
 
 	# Reset the index and working tree to the fetched HEAD
 	# (submodules are cloned in the subsequent sync step)
-	print_process "Resetting index & working tree to fetched HEAD"
+	dotlog::process "Resetting index & working tree to fetched HEAD"
 	git reset --hard FETCH_HEAD
 
 	# Remove any untracked files
-	print_process "Removing any untracked files"
+	dotlog::process "Removing any untracked files"
 	git clean -fd
 
-	[[ $? ]] && print_success "Repository has been initialized"
+	[[ $? ]] && dotlog::success "Repository has been initialized"
 
 	# Pull down the latest changes
-	print_process "Pulling down latest changes"
+	dotlog::process "Pulling down latest changes"
 	git pull --rebase origin main
 
-	[[ $? ]] && print_success "Repository has been updated"
+	[[ $? ]] && dotlog::success "Repository has been updated"
 fi
 
 # Install Homebrew formulae
 if ! type -P 'brew' &>/dev/null; then
-	print_error "brew not found"
+	dotlog::error "brew not found"
 	exit 1
 else
-	print_process "Installing Homebrew packages"
+	dotlog::process "Installing Homebrew packages"
 
 	brew update
 	brew upgrade
 	brew bundle --file="$INSTALL_DIR/opt/Brewfile"
 	brew cleanup
 
-	[[ $? ]] && print_success "Installed all Homebrew packages"
+	[[ $? ]] && dotlog::success "Installed all Homebrew packages"
 fi
 
 # Install Node packages
 if ! type -P 'npm' &>/dev/null; then
-	print_error "npm not found"
+	dotlog::error "npm not found"
 	exit 1
 else
-	print_process "Installing and updating npm packages"
+	dotlog::process "Installing and updating npm packages"
 	npm cache clean -f
 	n stable
 	install_packages npm_package "$INSTALL_DIR/opt/npm"
 
-	[[ $? ]] && print_success "Installed all Node packages"
+	[[ $? ]] && dotlog::success "Installed all Node packages"
 fi
 
 # Automatically set 1Password session after logging in
 if [ -x "$(command -v op)" ]; then
-	print_process "Configuring 1Password CLI"
+	dotlog::process "Configuring 1Password CLI"
 	printf "eval \$(op signin %s)\\n" "$USERNAME" >>"$HOME/.bash_profile.local"
 
-	[[ $? ]] && print_success "Configured 1Password CLI"
+	[[ $? ]] && dotlog::success "Configured 1Password CLI"
 fi
 
 if [ -x "$(command -v fzf)" ]; then
-	print_process "Installing FZF keybindings and fuzzy completion"
-	print_info "Do not say 'yes' to update the shell configuration, it's already set up"
+	dotlog::process "Installing FZF keybindings and fuzzy completion"
+	dotlog::info "Do not say 'yes' to update the shell configuration, it's already set up"
 	"$(brew --prefix)/opt/fzf/install"
 
-	[[ $? ]] && print_success "Installed FZF keybindings and fuzzy completion"
+	[[ $? ]] && dotlog::success "Installed FZF keybindings and fuzzy completion"
 fi
 
 # Install Gitmoji Fuzzy Hook
 if ! type -P 'git' &>/dev/null; then
-	print_error "git not found"
+	dotlog::error "git not found"
 	exit 1
 else
-	print_process "Installing Gitmoji"
+	dotlog::process "Installing Gitmoji"
 	git clone https://gitlab.com/raabf/gitmoji-fuzzy-hook.git "$HOME/.local/share/gitmoji-fuzzy-hook"
 	[ -d "$HOME/.local/bin" ] || mkdir -p "$HOME/.local/bin"
 	ln -sfn "$HOME/.local/share/gitmoji-fuzzy-hook/bin/gitmoji-fuzzy-hook-init.sh" "$HOME/.local/bin/gitmoji-fuzzy-hook-init"
 
-	[[ $? ]] && print_success "Installed Gitmoji"
+	[[ $? ]] && dotlog::success "Installed Gitmoji"
 fi
 
 if [[ "$OS" == "darwin" ]]; then
@@ -207,19 +206,19 @@ if [[ "$OS" == "darwin" ]]; then
 	if is_confirmed; then
 		brew install mas
 		brew bundle --file="$INSTALL_DIR/opt/Brewfile.macos"
-		[[ $? ]] && print_success "Installed all MacOS apps"
+		[[ $? ]] && dotlog::success "Installed all MacOS apps"
 	fi
 fi
 
 # Install Whalebrew packages
 if ! type -P 'whalebrew' &>/dev/null; then
-	print_error "whalebrew not found"
+	dotlog::error "whalebrew not found"
 	exit 1
 else
-	print_process "Installing and updating whalebrew packages"
+	dotlog::process "Installing and updating whalebrew packages"
 	install_packages whalebrew_package "$INSTALL_DIR/opt/Brewfile.whale"
 
-	[[ $? ]] && print_success "Installed all Whalebrew packages"
+	[[ $? ]] && dotlog::success "Installed all Whalebrew packages"
 fi
 
-[[ $? ]] && print_success "dotpackages installed."
+[[ $? ]] && dotlog::success "dotpackages installed."
